language: node_js
version: 1.0

node_js:
  - node

cache: yarn

script:
  - yarn ci

deploy:
  edge: true
  provider: npm
  email: accounts@francoisbest.com
  api_key:
    secure: NwiczayIHrewM9h9oG/LT2PWlrJcCeuleTJOpVypzRwBKFryOhLMUKWW8NeWkidJq56m5fptQeqifQ/xWNp+23XY6WO6ybRKC3cA1dF4Tf1atu0yEujKXtvPDfMb400YroNkcsb7ZhzVumO7TDYiPmpU90o8indX4F8WMlpNPqdZnHy15jY+ceTZvS41E5vtFWjtEhMH4jjhL1KCFOUjnLa34fG0H7pqoPoU19Im2Bv/6AfFrqyURHaYm8hmH6dkXQVgAWj8Q0PUQjg/LOvUZk/mKvvHpecy+XqLh7vWwBv94dLXOYGKEs7ZtKAWoZBvWVyoyNq1sSVZ18LviFSa5uXc8BdsNkWklanmQKmWoTEgTSd+ltaxVuUeiIZSNdLCZEkIxKK9Ej/sryjPL+gqxZLEA63roecvYna80IFEGj/XcAT5mGVpESb6UIzDJWizOLto+T/HB3RCoQyBYPvSM5Jgg6VUxXc5v0hAfQWmFfkcy1jyHsSiZ3sIxb2oaQ4rsKFrvuA7j6GshRlWJNkpiI2kCA5XVyXAe/fvLY4e9MkJJqlw6aEde4WYUHITHADG1H9gCTEKiVlYle3KUdaT3FXJV4uoqN1Psshw8yvAGI3chViaFcCYu8Tbr4NVokL5O2WZilDoPCOd77OhCr3PxWALnUBkkFyulxHKeZ83AGQ=
  on:
    tags: true
  skip_cleanup: true

notifications:
  slack:
    rooms:
      secure: PmwRHzT63UsRwtUeyhtQX/FoGFhrx0VrsU6p6sfDPHUUbWWQ4LM07Y7hYzrjzsep1znSVnFzJ9lcdSfi+Dji1E5sgxEGYw2obJKhdZKZ/iz1F3ePm4Nl+7G9/r9NhEb0ok4nuv1CWEcWqagqFWWClybYLGfKk94k/nNtHZreM1I0nyoaUwNiSDrxfrkQ5f0ynkZ375JAPMmKHqB9XWepQkU0vIlZH+CW3gESZqiTYiKCoHjr1nxjTOSVQ+44XhR+yb15PDB+XGdC5oAGGcbmxMi0vtn4gw38sFMkRgtNQhLdptzoFTV+wEyLe+fTmXO72lbCGRC5pqiSEf6mUEMpUB1ly0o5E89p7vK8l4GhQtRRCJFMa/+LL1VoWweJdurUtI0HTI5/zHlOkpblhEHAhHqC9P1VUFOZ11qTsaZ/qomZ3JaUKdVbZMRDI7h49S1GpFvoNtvWyhGVCHpp22VJr/ZYw9SMN26QdVrQro5RMEUjP9vAuvQ1ZWywozRqbWi1shtiak5f3KVEsCCLoVBbwYBHR2vJoHYuJiU8NdLPmo9wFVcwgTVPuMHNo0k+X4poZIeWhLBfve5xz9oM75/lLaHHp0PshLeeAU8KN24z5tKljuUGpvfW+ifeWLUoSb7934jfpcMEDUE5mQM2Pm2MMOFeVmSm9358YjEPEudIUUQ=
    on_success: change
    on_failure: always
